apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trinityid

resources:
  - 00-secret.yaml
  - 01-backup-pvc.yaml
  - 02-cronjob.yaml

# This base expects a backup PVC (ReadWriteMany backed by NFS) and a Secret with backup credentials.

patchesStrategicMerge:
  - patch-labels.yaml
  - patch-annotations.yaml
